### ISSUE TITLE
Apple iOS should now work..

### ISSUE THREAD

**Issue by willwade** [madcrow99/Bluetooth-HeadMouse-#2]
Cool project. Just a FYI your readme says Apple iOS devices wont work - they will now under iOS 13

Interesting you are using a mega and the rn-42. We are finding that the nrf52840 is a lot more reliable to work with - and using something like https://www.adafruit.com/product/4516 - may make the whole thing a lot smaller. I see why you have three bluetooth modules - to use on different devices. Thats one thing from reading the docs that the nrf52840 should be able to do. One idea is to just change the name of the BT device and toggle between three names -although I have to admit - I haven't worked it out yet!

Great stuff. Will add to https://openassistive.org

NB: Add a licence - https://choosealicense.com - it will make forks and future work on this a bit easier :)

**Comment by madcrow99** [comment]
Thanks for the information!

I used the mega for the 3 serial UART. I also use it for drive controls for
my chair so the mega is good for lots of pins.

I agree with you on the nrf. I actually made a head mouse this week with an
adafruit feather sense. It was so much easier as everything needed came
included on the board. Plus their examples and libraries are incredible.
BLE is nice too.

Mike
